[Feat] 시작 화면 제작
JobSeek-Void/ic-ec pull request #29
Opened 2023-05-20 14:10 UTC by ham2174

### OverView

- 카메라 / 갤러리 선택 화면이 구현되었습니다.
- 갤러리에서 사진 선택 이후 모자이크 기능으로 넘어갈 수 있습니다.
- 카메라 / 갤러리 버튼을 반응형으로 제작하였습니다.
---
### Archarving

- 반응형 UI가 현재 미완성이어서 추후 반응형 디자인이 나올 경우 변경 혹은 적응형디자인으로 교체
- 커스텀 갤러리 구현 필요

2023-05-20 15:01 UTC, EvergreenTree97 requested changes
고생하셨습니다! 리뷰 확인 부탁드려요!

2023-05-20 15:01 UTC, evergreentree97 commented on presentation/src/main/java/team/jsv/icec/ui/main/MainActivity.kt
> +    private val imagePath: String? by lazy { intent.getStringExtra("imagePath") }
viewmodel의 savedStateHandle에서 받아서 처리하면 Activity에서 imagePath에 대한 참조를 만들지 않을 수 있을 것 같네요

2023-05-20 15:01 UTC, evergreentree97 commented on presentation/src/main/java/team/jsv/icec/ui/main/start/StartActivity.kt
> +        Intent(this@StartActivity, MainActivity::class.java).apply {
제가 만들어 둔 확장 함수 사용하면 더 간단하게 사용할 수 있을 것 같습니다!
```suggestion
startActivityWithAnimation<MainActivity>(
    intentBuilder = {
        putExtra("imagePath", imagePath)
    }
)
```

2023-05-20 15:01 UTC, evergreentree97 commented on presentation/src/main/java/team/jsv/icec/ui/main/start/StartActivity.kt
> +            putExtra("imagePath", imagePath)
`Extras` 라는 object로 관리하는게 어떨까요?
intent로 전달하는 extra가 여러 곳에서 사용 되기도 해서 전역적으로 관리하는게 좋아보여요
```
object Extras{
    const val ImagePath = "ExtraImagePath"
}
```

2023-05-20 15:01 UTC, evergreentree97 commented on presentation/src/main/java/team/jsv/icec/ui/main/start/StartActivity.kt
> +            startActivity(Intent(this@StartActivity, CameraActivity::class.java))
```suggestion
            startActivityWithAnimation<CameraActivity>()
```

2023-05-20 15:01 UTC, evergreentree97 commented on presentation/src/main/java/team/jsv/icec/ui/main/start/StartActivity.kt
> +    private fun getPathFromUri(context: Context, uri: Uri): String? {
gallery에서 data를 가지고 오는 로직을 data layer에 두는건 어떨까요? 
장점 :
- gallery에서 이미지를 가져오는 로직을 usecase로 두어 프로젝트에서 재사용 가능
- gallery에서 image를 가져온다는 로직은 플랫폼 종속적이지 않을 수 있음
    - 추후 확장성을 봤을 때, 여러 플랫폼에서 사용 가능한 로직임
단점 : 
- 코드 량 증가
인데 장점이 가지는게 더 크다고 생각해서 제안해 봅니다

2023-05-21 05:21 UTC, jiiiiiyoon approved these changes
수고하셨습니당~

2023-05-22 16:12 UTC, ham2174 commented on presentation/src/main/java/team/jsv/icec/ui/main/start/StartActivity.kt
> +    private fun getPathFromUri(context: Context, uri: Uri): String? {
- 추후 작업해서 새로운 PR 올리겠습니다~!

2023-05-22 16:12 UTC, merged