[Refactor] 편집 기능 제거와 프로젝트 구조 수정
JobSeek-Void/ic-ec pull request #43
Opened 2023-05-29 05:46 UTC by ham2174

### OverView

- `Presentation` 모듈내의 파일 구조가 변경 되었습니다.
- 기존 `MosaicViewModel` 은 이제 `MainViewModel`로 명칭이 변경되었습니다.
- `MainViewModel`, `MosaicEvent`, `PictureState` 파일의 위치가 이제 `main` 디렉터리 하위에 배치됩니다.
- `편집` 기능 관련 작업들이 삭제되었습니다.
- `편집/모자이크` 분기 프래그먼트와 `편집` 프래그먼트가 삭제되었습니다.
- `nav_Gragh.xml`이 일부 수정되었습니다.
- `MainViewModel`의 `originalImage`와 `mosaicImage`가 늦은 초기화 변수로 바뀌었습니다.
  - 기존 `originalImage`와 `mosaicImage`는 **라이브 데이터**로 선언 되어있었습니다. 하지만, 해당 변수는 `MainActivity`에 존재하는 이미지 뷰에만 사용될 데이터이므로 값을 관찰할 필요성이 없어져, 늦은 초기화 변수로 바꾸었습니다. `MainActivity`에 존재하는 이미지의 변경은 `ScreenStep`에 따라 `PictureState`를 변경하는 로직으로 구성됩니다.

2023-05-29 06:23 UTC, EvergreenTree97 requested changes
디코에서 더 얘기해봐요~

2023-05-29 06:23 UTC, EvergreenTree97 commented on presentation/src/main/java/team/jsv/icec/ui/main/MainViewModel.kt
> +    var mosaicImage: String
ViewModel을 참조하는 어떤 클래스에서도, ViewModel의 내부 변수인 _originalImage를 변경할 수 있다는 점에서 캡슐화의 원칙이 완전히 깨져버리는 것 아닐까요?

2023-05-29 06:23 UTC, EvergreenTree97 commented on presentation/src/main/java/team/jsv/icec/ui/main/MainViewModel.kt
> +    private lateinit var _originalImage: File
제안하는건 _originalIamge, _mosaicImage 이 둘을 MainState로 묶어서 MainActivity에 대한 View Data를 단일 상태로 가지고 있는건 어떨까요?

2023-05-29 11:18 UTC, EvergreenTree97 approved these changes

2023-05-31 06:28 UTC, jiiiiiyoon approved these changes
수고하셨습니둥~(ง •_•)ง

2023-06-02 08:35 UTC, merged